workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      before_build:
        - cd ios
        - pod install --repo-update
    artifacts:
      - build/ios/ipa/*.ipa
