// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvVVnOjmVUO0J9vRufC9zSbTRdeFymv5o',
    appId: '1:779689342841:web:17f3ca2c5c37ddb72e21a8',
    messagingSenderId: '779689342841',
    projectId: 'zorem-24532',
    authDomain: 'zorem-24532.firebaseapp.com',
    storageBucket: 'zorem-24532.firebasestorage.app',
    measurementId: 'G-PS2Q6L7435',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzJ9qFChz8eKBR01hfR9m2MCxKXeDwLWA',
    appId: '1:779689342841:android:0ca8a3c33c6196872e21a8',
    messagingSenderId: '779689342841',
    projectId: 'zorem-24532',
    storageBucket: 'zorem-24532.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTh1w_T93BisUKqwOb3Vu4fJIvwoaMNCE',
    appId: '1:779689342841:ios:04e30f81c029fa3a2e21a8',
    messagingSenderId: '779689342841',
    projectId: 'zorem-24532',
    storageBucket: 'zorem-24532.firebasestorage.app',
    iosBundleId: 'com.example.trouveTonParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTh1w_T93BisUKqwOb3Vu4fJIvwoaMNCE',
    appId: '1:779689342841:ios:04e30f81c029fa3a2e21a8',
    messagingSenderId: '779689342841',
    projectId: 'zorem-24532',
    storageBucket: 'zorem-24532.firebasestorage.app',
    iosBundleId: 'com.example.trouveTonParking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvVVnOjmVUO0J9vRufC9zSbTRdeFymv5o',
    appId: '1:779689342841:web:b84122c1e331f2e52e21a8',
    messagingSenderId: '779689342841',
    projectId: 'zorem-24532',
    authDomain: 'zorem-24532.firebaseapp.com',
    storageBucket: 'zorem-24532.firebasestorage.app',
    measurementId: 'G-HT96S9BJVB',
  );

}